name: "Lint protobufs"

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-protos:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup buf tools
      uses: bufbuild/buf-setup-action@v1
    - name: Lint
      uses: bufbuild/buf-lint-action@v1